export type Spirit = {
  name: string,
  label: string,
}

export const SPIRITS = [
  { name: "Lightning's Swift Strike", label: "Lightning", },
  { name: "River Surges in Sunlight", label: "River", },
  { name: "Shadows Flicker Like Flame", label: "Shadows", },
  { name: "Vital Strength of the Earth", label: "Earth", },
  { name: "A Spread of Rampant Green", label: "Green", },
  { name: "Thunderspeaker", label: "Thunderspeaker", },
  { name: "Bringer of Drems and Nightmares", label: "BoDaN", },
  { name: "Ocean's Hungry Grasp", label: "Ocean", },
  { name: "Keeper of the Forbidden Wilds", label: "Keeper", },
  { name: "Sharp Fangs Behind the Leaves", label: "Fangs", },
  { name: "Heart of the Wildfire", label: "Wildfire", },
  { name: "Serpent Slumbering Beneath the Island", label: "Serpent", },
  { name: "Grinning Trickster Stirs Up Trouble", label: "Trickster", },
  { name: "Lure of the Deep Wilderness", label: "Lure", },
  { name: "Many Minds Move as One", label: "Many Minds", },
  { name: "Shifting Memory of Ages", label: "Memory", },
  { name: "Stone's Unyielding Defiance", label: "Stone", },
  { name: "Volcano Looming High", label: "Volcano", },
  { name: "Shroud of Silent Mist", label: "Mist", },
  { name: "Vengeance as a Burning Plague", label: "Vengeance", },
  { name: "Fractured Days Split the Sky", label: "Fractured Days", },
  { name: "Starlight Seeks Its Form", label: "Starlight", },
  { name: "Downpour Drenches the World", label: "Downpour", },
  { name: "Finder of Paths Unseen", label: "Finder", },
  { name: "Devouring Teeth Lurk Underfoot", label: "Teeth", },
  { name: "Eyes Watch from the Trees", label: "Eyes", },
  { name: "Fathomless Mud of the Swamp", label: "Mud", },
  { name: "Rising Heat of Stones and Sand", label: "Heat", },
  { name: "Sun-Bright Whirlwind", label: "Sun-Bright", },
  { name: "Ember-Eyed Behemoth", label: "Behemoth", },
  { name: "Hearth-Vigil", label: "Hearth", },
  { name: "Towering Roots of the Jungle", label: "Roots", },
  { name: "Breath of Darkness Down Your Spine", label: "Darkness", },
  { name: "Relentless Gaze of the Sun", label: "Sun", },
  { name: "Wandering Voice Keens Delerium", label: "Delerium", },
  { name: "Wounded Waters Bleeding", label: "Wounded Waters", },
  { name: "Dances Up Earthquakes", label: "Earthquake", },
]